[project]
name = "hydrate_prediction"
version = "0.1.0"
description = "Hydrate prediction project"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "pyarrow>=14.0.0",
]